# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.7.1
_src_path: gh:quickplates/meta
accountname: quickplates
description: Next.js app template ⚫
example: true
exampleaccountname: quickplates
exampledescription: Next.js app example ⚫
examplereponame: next-example
reponame: next
repourl: https://github.com/quickplates/next
type: app
